---
title: "Modelling Human Endurance: Power Law vs Critical Power - Figure 4"
output: html_document
---

```{r}
library("here")
library("tidyverse")
library("scales")
library("magrittr")
library("janitor")
library("RColorBrewer")
library("cowplot")
library("stats4") # provides nls() for non-linear least squares
library("hms")

options(scipen = 10000) # avoid scientific notation

# Colours
col_hyp <- "#F8766D"
col_pow <- "#00BFC4"

fig_4_data <- readRDS(here("figure_data","fig_4_data.RDS"))
fig_4_medium_data <- fig_4_data %>%
  filter(durations >= 120 & durations <= 840)
fig_4_non_medium_data <- fig_4_data %>%
  filter(durations < 120 | durations > 840)
  

```

# Figure 4A

```{r}
t<- seq(from = 1, to = 840 , length = 840)
T <- length(t)

###############################################################################
## Eliud Kipchoge - Jones 2019 Panel A 
###############################################################################

fig_4_A_data <- readRDS(here("figure_data","fig_4_A_data.RDS"))

fig_4_A_data %>%
  filter(time <= 860) %>%
  ggplot() +
  geom_line(mapping = aes(x = time, y = velocity, colour = model)) +
  geom_point(data = fig_4_medium_data , mapping = aes(x = durations,y = power), colour = "black") +
  scale_x_continuous(expand = c(0,0),breaks = c(0,120*c(1:7))) +
  scale_y_continuous(expand = c(0, 0),
                     breaks = c(2*(2:7))) +
  coord_cartesian(xlim =c(0,860), ylim = c(4,15)) +
  labs(x = "Duration [s]", y = "Velocity [m/s]", colour = "") +
  scale_colour_manual(
    values = c(col_hyp,col_pow),
    guide = guide_legend(
      override.aes = list(
        linetype = c("solid"),
        shape = c(NA)
      )
    )
  )+
  theme_classic() +
  theme(legend.position="none")
```

# Figure 4B


```{r}
fig_4_B_data <- readRDS(here("figure_data","fig_4_B_data.RDS"))

fig_4_B_data %>%
  filter(time <= 8600) %>%
ggplot() +
  geom_line(mapping = aes(x = time, y = velocity, colour = model)) +
  geom_point(data = fig_4_medium_data , mapping = aes(x = durations,y = power), colour = "black") +
  geom_point(data = fig_4_non_medium_data , mapping = aes(x = durations,y = power), shape = 17, colour = "black") +
  scale_x_continuous(expand = c(0, 0),breaks = c(0,1200*c(1:7))) +
  scale_y_continuous(expand = c(0, 0),
                     breaks = c(2*(2:7))) +
  coord_cartesian(xlim =c(0,8600), ylim = c(4,15)) +
  labs(x = "Duration [s]", y = "Velocity [m/s]", colour = "") +
  scale_colour_manual(
    values = c(col_hyp,col_pow),
    guide = guide_legend(
      override.aes = list(
        linetype = c("solid"),
        shape = c(NA)
      )
    )
  )+
  theme_classic() +
  theme(legend.position = c(0.8, 0.8))
```

# Figure 4C

```{r}
fig_4_C_data <- readRDS(here("figure_data","fig_4_C_data.RDS"))

fig_4_C_data %>%
  filter(time <= 8600) %>%
  ggplot() +
  geom_line(mapping = aes(x = time, y = distance, colour = model)) +
  geom_point(data = fig_4_medium_data , mapping = aes(x = durations,y = work), colour = "black") +
  geom_point(data = fig_4_non_medium_data , mapping = aes(x = durations,y = work), shape = 17, colour = "black") +
  scale_x_continuous(expand = c(0, 0),breaks = c(0,1200*c(1:7))) +
  scale_y_continuous(expand = c(0, 0),
                     breaks = c(0,10000*(1:5)), labels = c(0,10*(1:5))) +
  coord_cartesian(xlim =c(0,8600), ylim = c(0,43000)) +
  labs(x = "Duration [s]", y = "Distance [km]", colour = "") +
  scale_colour_manual(
    values = c(col_hyp,col_pow),
    guide = guide_legend(
      override.aes = list(
        linetype = c("solid"),
        shape = c(NA)
      )
    )
  )+
  theme_classic()+
  theme(legend.position="none")
```

```{r}
fig_4_D_data <- readRDS(here("figure_data","fig_4_D_data.RDS"))

fig_4_D_data  %>%
  filter(time <= 8600) %>%
  ggplot()+
  geom_line(mapping = aes(x = inv_t, y = velocity, colour = model)) +
  geom_point(data = fig_4_medium_data , mapping = aes(x = 1/durations,y = power), colour = "black") +
  geom_point(data = fig_4_non_medium_data , mapping = aes(x = 1/durations,y = power), shape = 17, colour = "black") +
  scale_x_continuous(expand = c(0, 0),breaks = c(0,0.002*c(1:3))) +
  scale_y_continuous(expand = c(0, 0),
                     breaks = (seq(from = 5.5, to = 7.5, by = 0.5))) +
  coord_cartesian(xlim =c(0,0.007), ylim = c(5.5,7.5)) +
  labs(x = "1/Duration [1/s]", y = "Velocity [m/s]", colour = "") +
  scale_colour_manual(
    values = c(col_hyp,col_pow),
    guide = guide_legend(
      override.aes = list(
        linetype = c("solid"),
        shape = c(NA)
      )
    )
  )+
  theme_classic()+
  theme(legend.position="none")
```



