---
title: "Modelling Human Endurance: Power Law vs Critical Power - Figure 3"
output: html_document
---

# Setup

```{r}
library("here")
library("tidyverse")

options(scipen = 10000) # avoid scientific notation

# Colours
col_hyp <- "#F8766D"
col_pow <- "#00BFC4"

my_theme <- theme_classic() +
  theme(legend.position = c(0.6, 0.9)) # places the legend inside the plot
```


# Figure 3
```{r}

durations   <- seq(from = 0, to = 180, length = 300)
n_durations <- length(durations)
S <- c(1600, 750)
E <- c(0.7, 0.9)
athletes <- c("Sprint specialist\n(large $S$, small $E$)", 
              "Endurance specialist\n(small $S$, large $E$)")
n_athletes <- length(athletes)


fig_3_data <- tibble(
  duration = rep(durations, times = n_athletes),
  speed = rep(S, each = n_durations),
  endurance = rep(E, each = n_durations),
  power = speed * duration^(endurance - 1),
  athlete = rep(athletes, each = n_durations)
)


labels <- unique(fig_3_data$athlete)

coords_sprint <- c(15, S[1] * 15^(E[1] - 1))
label_coords_sprint <- coords_sprint + c(10, 350)
coords_endure <- c(150, S[2] * 150^(E[2] - 1))
label_coords_endure <- coords_endure + c(0, 200)

fig_3_data %>%
  ggplot(mapping = aes(x = duration, y = power, linetype = athlete)) +
  geom_line(colour = col_pow, show.legend = FALSE) +
  scale_y_continuous(expand = c(0, 0)) +
  scale_x_continuous(expand = c(0, 0)) +
  coord_cartesian(ylim = c(0, 1500), xlim = c(0, max(fig_3_data$duration))) +
  labs(x = "Duration [s]", y = "Power [J/s]", linetype = "") +
  my_theme +
  annotate(
    geom       = "text", 
    x          = label_coords_sprint[1],
    y          = label_coords_sprint[2], 
    label      = labels[1],
    hjust      = -0.02, vjust = 0,
    lineheight = 1#,
  ) + 
  annotate(
    geom       = "curve", 
    xend       = coords_sprint[1],
    yend       = coords_sprint[2], 
    x          = label_coords_sprint[1] + 0.05, 
    y          = label_coords_sprint[2] - 20,
    curvature  = 0.05, 
    arrow      = arrow(length = unit(2, "mm")),
    alpha      = 1#,
  ) +
  annotate(
    geom       = "text", 
    x          = label_coords_endure[1],
    y          = label_coords_endure[2], 
    label      = labels[2],
    hjust      = 0.8, vjust = 0,
    lineheight = 1#,
  ) + 
  annotate(
    geom       = "curve", 
    xend       = coords_endure[1],
    yend       = coords_endure[2], 
    x          = label_coords_endure[1] + 0.05, 
    y          = label_coords_endure[2] - 20,
    curvature  = -0.2, 
    arrow      = arrow(length = unit(2, "mm")),
    alpha      = 1#,
  )
```
