---
title: "Large-data study in cycling"
output: html_notebook
editor_options: 
  chunk_output_type: console
---

```{r, include = FALSE}
library("here")
library("tidyverse")
library("magrittr")
library("lubridate")
library("stats4")

source(here("script", "compute_and_plot_errors.R"))
source(here("script", "gc_cleaning.R"))

rewrangle_data   <- FALSE
recompute_errors <- FALSE
```
Golden Cheetah data as of 09/06/2022

```{r, include = FALSE}

if (rewrangle_data) {
  
  gc_file_path <- here("data","gc_data")

  gc_files <- list.dirs(gc_file_path,recursive = FALSE)
  
  percentile <- calculate_percentiles(file_paths = gc_files,percentile = 95)
  
  df_gc <- clean_gc_data(file_paths = gc_files, percentile) %>% 
  ungroup() %>%
  select(rider_id,duration,mmp_value) %>%
  rename(id = rider_id,
         power = mmp_value) %>%
  mutate(distance = duration * power) # Distance is used here instead of work so that the later functions will work
  
  write_rds(df_gc, file = here("data", "df_gc.Rds"))
  
} else{
  df_gc <- read_rds(here("data", "df_gc.Rds"))
}

```


```{r}
if (recompute_errors) {
  
  compute_errors(
    data = df_gc,
    durations_min = 60 * c(0, 1, rep(2, times = 6)),
    durations_max = 60 * c(15, 15, 15, 16, 20, 30, 60, 240),
    n_efforts_min = 3,
    n_distances_min = 0
  ) -> df_errors_gc
  
  write_rds(df_errors_gc, file = here("data", "df_errors_gc.Rds"))
  
} else {

  df_errors_gc <- read_rds(here("data", "df_errors_gc.Rds"))
  
}
```


```{r}
plot_errors(
  data = df_errors_gc,
  file = file.path(path_to_figure_folder, "errors_df_errors_gc.tex"),
  show.legend = TRUE
) -> plot_gc
plot_gc
```



