---
title: "Large-data study in rowing"
output: html_notebook
editor_options: 
  chunk_output_type: console
---


```{r}
library("here")
library("tidyverse")
library("janitor")
library("magrittr")
library("readxl")


source(here("script", "compute_and_plot_errors.R"))

rewrangle_data   <- FALSE
recompute_errors <- FALSE
```


```{r}
# Calculates the duration (in seconds) associated with a given power
# (in J/s) and distance (in m) via the formula used in the original
# spreadsheet from https://www.researchgate.net/publication/325090221_Critical_Power_Calculator_for_C2_row_and_ski_ergometers_with_datasets.
compute_equivalent_duration <- function(power, distance) {
  return((2.8 / power)^(1 / 3) * distance)
}
# Same as above but calculates the equivalent distance from power and duration.
compute_equivalent_distance <- function(power, duration) {
  return((power / 2.8)^(1 / 3) * duration)
}
# Same as above but calculates the equivalent power from duration and distance.
compute_equivalent_power <- function(duration, distance) {
  return(2.8 * (distance / duration)^3)
}
```



# Dataset 1: Seiler's row and ski ergometer data set

Data source: 
<https://www.researchgate.net/publication/325090221_Critical_Power_Calculator_for_C2_row_and_ski_ergometers_with_datasets>

```{r}
if (rewrangle_data) {
  read_excel(here("figure_data", "seiler_row_ski_ergometer.xlsx"), sheet = 2) %>%
    clean_names() %>%
    mutate(id = 1:n()) %>%
    select(!athlete) %>%
    pivot_longer(cols = !id, names_to = "type", values_to = "power") %>%
    mutate(duration =
      case_when(
        type == "x1_minute" ~ 60,
        type == "x60_minutes" ~ 3600,
        TRUE ~ compute_equivalent_duration(power, parse_number(type, locale = locale(grouping_mark = "_")))
      )
    ) %>%
    select(!type) %>%
    mutate(distance = compute_equivalent_distance(power, duration)) -> df_seiler
  
  write_rds(df_seiler, file = here("figure_data", "df_seiler.Rds"))
} else {
  df_seiler <- read_rds(here("figure_data", "df_seiler.Rds"))
}
```





# Dataset 2: Season's bests from nonathlon.om

Data source: 
<https://www.nonathlon.com>

```{r}
if (rewrangle_data) {
    
  file_dir   <- here("figure_data", "nonathlon")
  file_names <- list.files(file_dir, full.names = FALSE)
  files      <- paste(file_dir, file_names, sep = "/")
  colnames <- c("position", "name", "total", "gender", "weight", "category", "500", "1000", "2000", "5000",	"6000",	"10000", 	"30min", "60min", "21097.5", "42195", "+", "year")
  
  df_nonathlon <- tibble()
  for (i in seq_along(files)) {
    n_rows <- nrow(read_tsv(files[i], skip = 1, col_names = FALSE, col_types = cols(.default = "c")))
    for (j in 1:(n_rows / 2)) {
      df_aux <- read_tsv(files[i], 
                         skip = 1 + 2 * (j - 1), 
                         n_max = 2, 
                         col_names = FALSE, 
                         col_types = cols(.default = "c")) # read all columns as character
      df_aux_1 <- df_aux %>% slice(1)
      df_aux_2 <- df_aux %>% slice(2)
      for (k in 1:10) {
        df_aux_1[1, 6 + k] <- df_aux_2[1, k]
      }
      df_nonathlon %<>% bind_rows(df_aux_1) %>% 
        mutate(year = parse_number(file_names[i]))
    }
  }
  
  df_nonathlon %<>% 
    set_colnames(colnames) %>%
    mutate(id = 1:n()) %>%
    select(!position) %>%
    select(id, year, everything()) %>%
    pivot_longer(
      cols = c("500", "1000", "2000", "5000", "6000", "10000", "21097.5", "42195", "30min", "60min"), 
      names_to = "type", 
      values_to = "duration"
    ) %>%
    filter(duration != "-") %>%
    mutate(
      distance = case_when(
        type %in% c("30min", "60min") ~ duration,
        TRUE ~ type
      )
    ) %>%
    mutate(
      duration = case_when(
        type == "30min" ~ "30:00.0",
        type == "60min" ~ "1:00:00.0",
        TRUE ~ duration
      )
    ) %>%
    mutate(
      duration = case_when(
        str_count(duration, "\\:") == 1 ~ as.double(lubridate::ms(duration)),
        str_count(duration, "\\:") == 2 ~ as.double(lubridate::hms(duration)),
        TRUE ~ 0
      )
    ) %>%
    mutate(distance = parse_number(distance)) %>%
    filter(duration > 0) %>%
    filter(distance > 0) %>%
    mutate(power = compute_equivalent_power(duration, distance)) %>%
    select(!type) %>%
    select(!`+`)
  
  write_rds(df_nonathlon, file = here("figure_data", "df_nonathlon.Rds"))
} else {
  df_nonathlon <- read_rds(here("figure_data", "df_nonathlon.Rds"))
}
```


```{r}
if (recompute_errors) {
    
  compute_errors(
    data = df_seiler,
    durations_min = 60 * c(1, 2, 2),
    durations_max = 60 * c(20, 20, 60),
    n_efforts_min = 3,
    n_distances_min = 0
  ) -> df_errors_seiler
  
  # Remove some athletes who have reported unrealistically high powers
  df_nonathlon %>% filter(power >= 1300) %>% pull(id) %>% unique() -> suspicious_IDs
  
  compute_errors(
    data = df_nonathlon %>% filter(!(id %in% suspicious_IDs)),
    durations_min = 60 * c(1, 2, 2, 2, 2),
    durations_max = 60 * c(20, 20, 25, 30, 240),
    # durations_min = 60 * c(2, 2, 2, 2, 2),
    # durations_max = 60 * c(15, 20, 25, 30, 240),
    n_efforts_min = 3,
    n_distances_min = 0
  ) -> df_errors_nonathlon
  
  write_rds(df_errors_seiler, file = here("figure_data", "df_errors_seiler.Rds"))
  write_rds(df_errors_nonathlon, file = here("figure_data", "df_errors_nonathlon.Rds"))
  
} else {
  
  df_errors_seiler    <- read_rds(here("figure_data", "df_errors_seiler.Rds"))
  df_errors_nonathlon <- read_rds(here("figure_data", "df_errors_nonathlon.Rds"))
  
}
```


```{r}
plot_errors(
  data = df_errors_seiler,
  width = 1.7,
  show.legend = FALSE
) -> plot_seiler


plot_errors(
  data = df_errors_nonathlon,
  width = 5,
  show.legend = TRUE
) -> plot_nonathlon


# df_errors_both <- bind_rows(
#   df_errors_seiler %>% mutate(data_source = "Seiler"),
#   df_errors_nonathlon %>% mutate(data_source = "Nonathlon")
# ) %>%
# mutate(data_source = factor(data_source, levels = c("Seiler", "Nonathlon")))
# plot_errors(
#   data = df_errors_both,
#   width = 5,
#   show.legend = TRUE,
#   facet_by_data_source = TRUE
# ) -> p_both
# p_both

```



<!-- ```{r} -->
<!-- # Check the profiles of those athletes who have at least three efforts  -->
<!-- # between 2 and 15 minutes: -->

<!-- # duration_cat <- "2--15" -->
<!-- # df_errors_nonathlon %>% -->
<!-- #   filter(duration == duration_cat) %>% -->
<!-- #   select(id, n_powers) %>% -->
<!-- #   distinct() %>% -->
<!-- #   pull(id) -> ids -->
<!-- #  -->
<!-- # # None of these have efforts shorter than 2 minutes (because this selects for -->
<!-- # # "slow" rowers whose 500-m time is above 2 minutes). -->
<!-- # df_nonathlon %>% -->
<!-- #   filter(id %in% ids) %>% -->
<!-- #   filter(distance == 500) -->
<!-- #  -->


<!-- duration_cat <- "1--20" -->

<!-- ids <- df_errors_nonathlon %>% -->
<!--   filter(duration == duration_cat) %>% -->
<!--   filter(error > 10^(-10)) %>% -->
<!--   pivot_wider(names_from = model, values_from = error) %>% -->
<!--   mutate(error_ratio = `Power law` / Hyperbolic) %>% -->
<!--   select(id, error_ratio) %>% -->
<!--   filter(error_ratio > 1) %>% -->
<!--   pull(id) -->

<!-- df_errors_nonathlon %>%  -->
<!--   filter(duration == duration_cat) %>% -->
<!--   filter(id %in% ids) %>% -->
<!--   distinct() %>% -->
<!--   ggplot(mapping = aes(x = n_powers)) + -->
<!--   geom_histogram(bins = 50) -->

<!-- df <- tibble() -->
<!-- ids <- ids[1:min(20, length(ids))] -->
<!-- DURATIONS <- seq(from = 10, to = 3600 * 4, length = 1000) -->
<!-- for (i in 1:length(ids)) { -->
<!--   df_nonathlon %>% -->
<!--     filter(id == ids[i]) %>% -->
<!--     filter(duration >= 60, duration <= 15 * 60) -> df_aux -->
<!--     power <- df_aux$power -->
<!--     duration <- df_aux$duration -->

<!--   lm_hyp <- lm(data = df_aux, formula = power ~ I(1 / duration)) -->
<!--   lm_pow <- lm(data = df_aux, formula = I(log(power)) ~ I(log(duration))) -->
<!--   cp <- coef(lm_hyp)[1] -->
<!--   w_prime <- coef(lm_hyp)[2] -->
<!--   E <- coef(lm_pow)[2] + 1 -->
<!--   S <- exp(coef(lm_pow)[1]) -->

<!--   df %<>% bind_rows(tibble( -->
<!--     id = ids[i], -->
<!--     duration = DURATIONS, -->
<!--     power = w_prime / DURATIONS + cp, -->
<!--     model = "Hyperbolic" -->
<!--   )) -->
<!--   df %<>% bind_rows(tibble( -->
<!--     id = ids[i], -->
<!--     duration = DURATIONS, -->
<!--     power = S * DURATIONS^(E - 1), -->
<!--     model = "Power law" -->
<!--   )) -->
<!-- } -->

<!-- range_powers <- df_nonathlon %>% filter(id %in% ids) %>% pull(power) %>% range() %>% multiply_by(c(0.95, 1.05)) -->

<!-- df %>% -->
<!--   ggplot(mapping = aes(x = duration, y = power, colour = model)) + -->
<!--   geom_line() + -->
<!--   facet_wrap(~id) + -->
<!--   geom_point(data = df_nonathlon %>% filter(id %in% ids) %>% select(id, duration, power), mapping = aes(x = duration, y = power), colour = "black", inherit.aes = FALSE) + -->
<!--   coord_cartesian(ylim = range_powers, xlim = c(1, 15) * 60) -->
<!-- ``` -->


```{r}

```

